#!/bin/bash -v

echo "*****Begin executing*** "
echo "Wait a bit for the network"
sleep 15s

echo "list data template variable"
echo ${region}
echo ${jenkins_s3_bucket}

aws configure set default.region ${region}
yum update -y
yum install docker -y
service docker start
echo "docker setup & started"
docker version
chmod 766 /var/run/docker.sock


curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
echo "docker-compose setup"
docker-compose -v

InstanceID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
mkdir -p /var/jenkins_home/

curl -O -L https://s3-us-west-2.amazonaws.com/em-devops-terraform/utilities/jenkins/jenkins.zip
unzip jenkins.zip
cd jenkins
pwd
ls

./create_jenkins_stack_docker.sh up

sleep 60s

echo "s3 bucket mounting as ec2 volume"
yum install -y gcc libstdc++-devel gcc-c++ fuse fuse-devel curl-devel libxml2-devel mailcap automake openssl-devel git
git clone https://github.com/s3fs-fuse/s3fs-fuse
cd s3fs-fuse/
./autogen.sh
./configure --prefix=/usr --with-openssl
make
make install

s3fs --version
s3fs -o iam_role="$( curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/ )" -o url="https://s3.${region}.amazonaws.com" -o endpoint=${region} -o dbglevel=info -o curldbg -o allow_other -o use_cache=/tmp -o nonempty ${jenkins_s3_bucket} /var/jenkins_home
ps -aef | grep s3fs

#service docker stop
#service docker start

echo "user_data is done"
